### ISSUE TITLE
Symantec certs are failing

### ISSUE THREAD

**Issue by adenbley** [iridium-browser/tracker#124] opened 2017-01-09 19:31 UTC
getting a `Failed to load resource: net::ERR_INSECURE_RESPONSE` for many sites. most notable are amazon.com and bitbucket. looking into this it was fixed in chromium 55, but this issue completely breaks iridium on these, major, sites.

**Comment by longsleep** [comment] 2017-01-13 09:27
For reference, this issue is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=664177 and starts to appear 10 weeks after build date.

On the more wider scale, the 10 weeks state for CT logs needs investigation.

**Comment by longsleep** [comment] 2017-01-14 08:25
Following up on this, https://news.ycombinator.com/item?id=12953172 has some nice background information about the CT time bomb and more.

**Comment by neuhaus** [comment] 2017-02-14 12:50
Is there an ETA when this blocker will be fixed? I have to use another browser for now.

**Comment by TheBauwssss** [comment] 2017-03-02 16:45
I have found a temporary workaround for this problem. Right click the shortcut and add the flag

`--force-fieldtrials=*EnforceCTForProblematicRoots/Disabled/`

to the end of the target. 

![image](https://cloud.githubusercontent.com/assets/1992977/23517162/de603f7a-ff6f-11e6-9bc3-b3cb0fc13928.png)

Source: https://bugs.chromium.org/p/chromium/issues/detail?id=664177#c72

**Comment by tonialb** [comment] 2017-03-03 02:00
@TheBauwssss 
Nice find thanks for sharing. ;-)

**Comment by neuhaus** [comment] 2017-03-08 14:02
After updaing Iridium to version `54.0-0ubuntu2~iridium0` the issue appears to be resolved.

**Comment by medozas** [comment] 2017-03-11 11:51
Issue has been fixed with Windows and Ubuntu builds and continue to fix this for the other builds as well.

**Closed by medozas** 2017-03-11 11:51 UTC
