### ISSUE TITLE
Installed extensions (apps) don't (auto)update

### ISSUE THREAD

**Issue by paultheweird** [iridium-browser/tracker#183] opened 2017-11-21 19:33 UTC
I'm using Iridium on OpenBSD to have a desktop Signal client (and an awesome webbrowser, of course). Installing and using the signal client works fine, but the app does not get auto updated. This may be intentional. However, going to chrome://extensions, enabling 'developer mode' and then clicking "update extensions now" still doesn't update the app.

Signal complains it's no longer up-to-date and offers an update button itself, but that too doesn't work. I've tried restarting the browser after hitting update, but am unable to get this to update. The only recourse is removing the extension and adding it again. That's not ideal - is there a better way?

**Comment by souldanger** [comment] 2017-11-22 09:10
duplicate of #146

**Closed by souldanger** 2017-11-22 09:10 UTC
