### ISSUE TITLE
Unable to update extensions through the menu

### ISSUE THREAD

**Issue by HairyMilkshakes** [iridium-browser/tracker#159] opened 2017-07-10 15:30 UTC
Hello,

I've been having an issues where I am unable to update extensions through the developer menu. Do I have to manually update them individually? If so, how can I do that?

Thanks!

**Comment by souldanger** [comment] 2017-10-20 18:27
Hi
let me suggest you try to delete to old version and install the new extension.
Unfortunately the trash can in chrome://extensions/ does not work.
Therefore please click on the extension icon right hand side of the address bar to delete the extension.

Updating extensions depends on the extension - if extension is managed by Google's PlayStore it wont work, as Iridium is blocking connections to PlayStore.

Thanks!

**Comment by HairyMilkshakes** [comment] 2017-10-23 00:54
Thanks for the reply - didn't know Iridium natively blocks connection to the Play store, which is why the extensions aren't updating.

Is there a best practice when it comes to maintaining them in this instance? I only have a folder set up and manually check for updates at interval.

**Comment by minusf** [comment] 2017-10-25 20:29
duplicate of #146

**Comment by souldanger** [comment] 2017-12-14 16:05
Hello
unfortunately, there is no better practise than checking manually occasionally.
Any automation process would have to call home to the extension or Play Store to find out if there is any update available.

**Closed by souldanger** 2017-12-14 16:05 UTC

**Comment by minusf** [comment] 2017-12-15 13:31
i might be mistaken, but for me the problem is not manually checking, but manually setting up all the plugins again as i have remove and readd them.
