### ISSUE TITLE
Loadind traced 

### ISSUE THREAD

**Issue by spinalgr1990** [iridium-browser/tracker#366] opened 2022-10-16 09:41 UTC
It shows me the following annoying message when I select a text and hit search with google

**Loadind traced URL: trk:113**

![traced](https://user-images.githubusercontent.com/63348163/196028671-db9852a0-b170-4f2a-b56a-3023cdc5f832.png)

**Comment by souldanger** [comment] 2022-10-16 15:36
Duplicate of #316

**Closed as completed by souldanger** 2022-10-16 15:36 UTC
