### ISSUE TITLE
Iridium contacting Google immediately after install and first start?

### ISSUE THREAD

**Issue by kaksikanaa** [iridium-browser/tracker#138] opened 2017-04-08 08:11 UTC
Hello!

I've just installed Iridium from the download page and by it's instructions to my Linux Mint. After the first start and by going to my own owncloud website, Iridium gave almost immediately  this error/warning:

"Loading traced URL:trk:173:https://redirector.gvt1.com/edged/chrome/dict/en-us-7-1.bdic"

Whati is happening here? There only few wise comments about this event but nothing clear about it. The basic domain is Google's I've presume -> Can anyone give any light on this issue?

BR

**Comment by longsleep** [comment] 2017-04-08 11:12
Iridium is fetching spelling correction dictionaries from Google shortly after you have typed something for the first time.

Duplicate of https://github.com/iridium-browser/tracker/issues/2

**Closed by longsleep** 2017-04-08 11:12 UTC
Labels: duplicate, Google request

**Comment by kaksikanaa** [comment] 2017-04-10 10:18
Ok, thanks! Did not noticed that it was already on the list, sorry.
