### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by Dvichous** [iridium-browser/tracker#311] opened 2020-11-04 23:20 UTC
I can not sync the iridium browser to my google account every time I try I get an error page regardless of the computer/laptop (See Bellow)

404. That’s an error.

The requested URL was not found on this server. That’s all we know.

Thank You
Dave Kellum

**Comment by jengelh** [comment] 2020-11-04 23:42
There is an item for that on https://iridiumbrowser.de/faq .

**Comment by jengelh** [comment] 2020-11-06 12:35
probably duplicate of #297 .

**Closed as completed by jengelh** 2020-11-06 12:35 UTC

**Comment by Weissnix4711** [comment] 2021-05-22 13:05
Hi. Sorry to bump this.

Sync works (on chromium, I have not yet tested with iridium), after following the steps [here](http://www.chromium.org/developers/how-tos/api-keys), under `Providing Keys at Runtime`. Though, it only works when part of the group google-browser-signin-testaccounts@chromium.org. Could anyone explain the purpose of this group, and why sync fails without it?

Also, should this even work anymore? I thought Google disabled sync for chromium and derivatives?
