### ISSUE TITLE
Not able to Install Extensions from Chrome Web Store at all

### ISSUE THREAD

**Issue by GormTheOld** [iridium-browser/tracker#277] opened 2020-05-21 16:09 UTC
I am not sure if this is a bug or not, but I am not at all able to install any Extension from Chrome Web Store.

The extensions I am trying to install is HTTPS Everywhere, uBlock Origin, and NoScript.

When pressing "Add to Chrome" I get the usual "Add extension" pop-up dialog box, but after acepting it just says "Checking..." like forever never installing any of the extensions.

Iridium version is 2020.04 (Official Build) (64-bit)
Windows version is Windows 10 Pro 1909

Thank you.

**Comment by souldanger** [comment] 2020-05-21 16:13
Hi
also running Https Everywhere and ublock and update both frequently w/o any issues.
do you have any other extensions running that might block the web store?

**Comment by GormTheOld** [comment] 2020-05-21 18:40
Hi,

Thanks for your follow up souldanger. The attempt was my first run with Iridium portable, so I have not been able to install any extensions at all. Regarding portable, I forgot to list that in my initial post. Sorry bout that.

**Comment by souldanger** [comment] 2020-05-21 19:27
no worries!
do you run 32 or 64-bit version?

**Comment by GormTheOld** [comment] 2020-05-21 19:46
64-bit :)

**Comment by johbru0** [comment] 2020-05-21 20:48
I am also running iridiumbrowser-2020.04.81.0-x64.exe and am having the exact same problem. I deleted all the extensions i originally had loaded into the browser and since then i've tried every way known to man to try to get some of them back. No matter what i try or which extension my browser also gives me the same responses as GormTheOld mentioned earlier. John

**Comment by souldanger** [comment] 2020-05-22 09:35
Hi guys,
i can confirm that there seems to be an issue with extensions on the portable version.
At this stage I am not entirely sure what the issue is. All I found out is that is has something to do with the user profile at  `C:\Users\%user%\AppData\Local\Iridium\User Data\`.
i.e. if you use the standard version and install extensions, these will be added automatically to the portable version, but if you only use the portable version you cannot add any extension.
I am not sure why and will therefore try to speak to the developer early next week and will let you know the verdict.
Thank you for your patience.

**Comment by GormTheOld** [comment] 2020-05-22 18:28
Thank you for pursuing this souldanger. Really appreciate it.
So that it is mentioned I am using a shortcut with the "...\IridiumPortable\iridium.exe --user-data-dir=UserData" configuration option. So the user data folder is in "...\IridumPortable\UserData".

That said you are refering to Windows Users folder, so it seems like user data folder location is not part of the the issue.

**Comment by kaleidoscopique** [comment] 2020-05-22 21:21
Hi guys!

I just changed my macbook (so I needed to reinstall everything from scratch) and I got exactly the same issue on my fresh install (64 bits, download from here: https://iridiumbrowser.de/downloads/macos).

I got the regular popup asking me to accept the installation, then "checking..." and nothing else.

Edit: I found this guy (https://www.reddit.com/r/privacytoolsIO/comments/gjpx0q/cant_install_chrome_extensions_with_iridium/) with the same issue.

**Comment by souldanger** [comment] 2020-05-23 05:50
@kaleidoscopique
thank your for the input.
we will address the issue and hope to solve this with the next release.
Please accept our apologies for the inconvenience.

**Comment by kaleidoscopique** [comment] 2020-05-23 08:12
If you guys don't want to switch to another browser until this bug is fixed, you can download an older version (this one for OS/X works fine : https://downloads.iridiumbrowser.de/macos/2020.01-0/), install your extensions, then upgrade to the latest version directly from Iridium itself.

**Comment by souldanger** [comment] 2020-05-23 09:19
Thanks Stéphane!!!

**Comment by GormTheOld** [comment] 2020-05-24 11:41
Thank you for your info @kaleidoscopique . I downloaded the .crx files by using the script provided by 'gleepenia' over at Reddit. Going to the homepage of the extension and then running the script as a bookmark. It works fine and I could just drop the downloaded .crx file into the Iridium Extensions page in Developer Mode. It worked fine with NoScript and uBlock Origin, but with HTTPS Everywhere I got a "This extension may have been corrupted" message. So HTTPS Everywhere doesn't work. When pressing 'Repair' Iridium removes it completely.

When doing the above it is not possible to remove the extensions by pressing 'remove'. So one have to go to the '\User Data\Default\Extensions' folder and delete them manually. If I have understood it correctly extension settings is stored in '\User Data\Default\Local Extension Settings , ...\Managed Extension Settings , and ...\Sync Extension Settings. If there are other places that I have missed please tell :)

**Comment by metapea** [comment] 2020-05-25 17:44
> I got the regular popup asking me to accept the installation, then "checking..." and nothing else.

And i thought it was just me that was getting that, i was told it was just autoblock when i reported it before.
Hopfully it will get fixed.

**Comment by souldanger** [comment] 2020-05-26 05:47
@metapea 
Please accept my apologies for the misguidance!
I had Iridium Broser installed on all my machines and therefore, didn't find the bug in the first place. A couple of days ago an extension issue with the portable version was reported and I found the bug, by wiping Iridium and reinstalling.
Disgracefully the bug only appears on latest Windows and macOS release, while all Linux builds are fully working.
It will be fixed with the next release.
Now

**Comment by johbru0** [comment] 2020-05-26 07:50
Going back one release also fixed both my tab and extension issues. I also found that if one installs the Privacy Possum extension it prevents some normal pages from loading (such as ProtonMail.com) and that it also interferes with other browsers loading perfectly good pages. Since in deleted it i'm noticing all the browsers i use, especially Iridium, now work perfectly fine both inside and outside Sandboxie. Thanks for your dedication and help with Iridium. I strongly prefer using it and look forward to the next release if it continues to allow tabs to load automatically and a careful selection of extension to be installed or deleted. Thank you, John

**Comment by medozas** [comment] 2020-06-03 17:06
Fix has been deployed with 2020.04.81.1 which is online now. Thanks for your bugreport!

**Closed as completed by medozas** 2020-06-03 17:06 UTC
Labels: bug
