### ISSUE TITLE
Extensions being listed as "Not From the Chrome Web Store"

### ISSUE THREAD

**Issue by coffeymug** [iridium-browser/tracker#182] opened 2017-11-21 19:33 UTC
I went to look at the list of extensions that I have and noticed for all of them it says "Not from the Chrome Web Store" beneath each one. I tried to install a new addon using the "Get more extensions" link at the bottom of the page. After I had installed the new addon it was also listed as not being from the Chrome store.

**Comment by souldanger** [comment] 2017-11-22 09:10
duplicate of #146

**Closed by souldanger** 2017-11-22 09:10 UTC
